# Site settings
title: "Sugiyama Research Group"
email: "sugiyama.outcomes.lab@gmail.com"
description: "The website of the Sugiyama Research Group."
baseurl: ""
url: "https://sugiyamaoutcomeslab.github.io"

# Build settings
markdown: kramdown

permalink: pretty

exclude:
  - run.sh

collections:
  - publications
  - projects

collections:
  projects:
    output: true